// clmWeb/admin-pc/src/views/Login.vue
<template>
  <div class="login-container">
    <div class="login-box">
      <h2>餐饮点餐系统</h2>
      <h3>商户管理端</h3>
      <el-form ref="loginForm" :model="form" label-width="80px" class="login-form">
        <el-form-item label="手机号" prop="phone">
          <el-input v-model="form.phone" placeholder="请输入手机号" />
        </el-form-item>
        <el-form-item label="密码" prop="password">
          <el-input v-model="form.password" type="password" placeholder="请输入密码" />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="handleLogin" class="login-btn">登录</el-button>
        </el-form-item>
      </el-form>
      <div class="tips">
        <p>平台管理员：13800138000 / 123456</p>
        <p>商户管理员：13800138001 / 123456</p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { ElMessage } from 'element-plus'
import { auth } from '../utils/api'

const form = reactive({
  phone: '',
  password: ''
})

const loginForm = ref(null)

const handleLogin = async () => {
  if (!form.phone || !form.password) {
    ElMessage.warning('请输入手机号和密码')
    return
  }
  
  try {
    const res = await auth.login(form)
    if (res.code === 200) {
      localStorage.setItem('token', res.data.token)
      localStorage.setItem('user', JSON.stringify(res.data.user))
      ElMessage.success('登录成功')
      setTimeout(() => {
        window.location.href = '/'
      }, 1000)
    } else {
      ElMessage.error(res.message)
    }
  } catch (error) {
    ElMessage.error('登录失败，请稍后重试')
  }
}
</script>

<style scoped>
.login-container {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.login-box {
  background: white;
  padding: 40px;
  border-radius: 12px;
  box-shadow: 0 10px 40px rgba(0, 0, 0, 0.1);
  width: 400px;
  text-align: center;
}

.login-box h2 {
  color: #303133;
  margin-bottom: 8px;
  font-size: 24px;
}

.login-box h3 {
  color: #909399;
  margin-bottom: 30px;
  font-size: 14px;
  font-weight: normal;
}

.login-form {
  margin-bottom: 20px;
}

.login-btn {
  width: 100%;
  height: 40px;
}

.tips {
  text-align: left;
  padding-top: 10px;
  border-top: 1px solid #f0f0f0;
}

.tips p {
  font-size: 12px;
  color: #999;
  margin-bottom: 5px;
}
</style>

// suTT/frontend/src/components/Login.jsx

import React, { useState } from 'react';
import axios from 'axios';

function Login({ onLogin }) {
  const [isRegister, setIsRegister] = useState(false);
  const [formData, setFormData] = useState({
    username: '',
    password: '',
    phone: '',
    email: '',
    code: ''
  });
  const [error, setError] = useState('');

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    
    try {
      let response;
      if (isRegister) {
        response = await axios.post('http://localhost:8080/api/auth/register', formData);
      } else {
        response = await axios.post('http://localhost:8080/api/auth/login', {
          account: formData.username,
          password: formData.password
        });
      }
      
      if (response.data.code === 200) {
        localStorage.setItem('token', response.data.data.token);
        localStorage.setItem('user', JSON.stringify(response.data.data.user));
        onLogin(response.data.data.user);
      }
    } catch (err) {
      setError(err.response?.data?.message || '操作失败');
    }
  };

  return (
    <div className="login-container">
      <div className="login-box">
        <h2>{isRegister ? '注册' : '登录'}</h2>
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label>{isRegister ? '用户名' : '账号'}</label>
            <input
              type="text"
              name="username"
              value={formData.username}
              onChange={handleChange}
              placeholder={isRegister ? '请输入用户名' : '请输入账号/手机号/邮箱'}
              required
            />
          </div>
          
          <div className="form-group">
            <label>密码</label>
            <input
              type="password"
              name="password"
              value={formData.password}
              onChange={handleChange}
              placeholder="请输入密码"
              required
            />
          </div>
          
          {isRegister && (
            <>
              <div className="form-group">
                <label>手机号（可选）</label>
                <input
                  type="text"
                  name="phone"
                  value={formData.phone}
                  onChange={handleChange}
                  placeholder="请输入手机号"
                />
              </div>
              <div className="form-group">
                <label>邮箱（可选）</label>
                <input
                  type="email"
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                  placeholder="请输入邮箱"
                />
              </div>
            </>
          )}
          
          {error && <div className="error-message">{error}</div>}
          
          <button type="submit" className="btn btn-primary">
            {isRegister ? '注册' : '登录'}
          </button>
        </form>
        
        <div className="toggle-link">
          <a href="#" onClick={(e) => { e.preventDefault(); setIsRegister(!isRegister); }}>
            {isRegister ? '已有账号？立即登录' : '没有账号？立即注册'}
          </a>
        </div>
      </div>
    </div>
  );
}

export default Login;
