// clmWeb/admin-h5/src/views/Login.vue
<template>
  <div class="login-container">
    <div class="logo-area">
      <div class="logo">🍽️</div>
      <h1>餐饮管理</h1>
      <p>商户管理端</p>
    </div>
    <van-form @submit="handleLogin">
      <van-field v-model="phone" label="手机号" placeholder="请输入手机号" type="number" />
      <van-field v-model="password" label="密码" placeholder="请输入密码" type="password" />
      <div style="margin-top: 20px;">
        <van-button type="primary" block size="large" native-type="submit">登录</van-button>
      </div>
    </van-form>
    <div class="tips">
      <p>平台管理员：13800138000 / 123456</p>
      <p>商户管理员：13800138001 / 123456</p>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { showToast } from 'vant'
import { auth } from '../utils/api'

const phone = ref('')
const password = ref('')

const handleLogin = async () => {
  if (!phone.value || !password.value) {
    showToast('请输入手机号和密码')
    return
  }
  
  try {
    const res = await auth.login({ phone: phone.value, password: password.value })
    if (res.code === 200) {
      localStorage.setItem('token', res.data.token)
      localStorage.setItem('user', JSON.stringify(res.data.user))
      showToast('登录成功')
      setTimeout(() => {
        window.location.href = '/'
      }, 1000)
    } else {
      showToast(res.message)
    }
  } catch (error) {
    showToast('登录失败')
  }
}
</script>

<style scoped>
.login-container {
  min-height: 100vh;
  padding: 40px 20px;
  background: linear-gradient(180deg, #667eea 0%, #764ba2 100%);
}

.logo-area {
  text-align: center;
  margin-bottom: 40px;
}

.logo {
  font-size: 80px;
  margin-bottom: 20px;
}

.logo-area h1 {
  color: white;
  font-size: 28px;
  margin-bottom: 8px;
}

.logo-area p {
  color: rgba(255, 255, 255, 0.8);
  font-size: 14px;
}

.tips {
  margin-top: 30px;
  padding: 15px;
  background: rgba(255, 255, 255, 0.1);
  border-radius: 10px;
}

.tips p {
  color: white;
  font-size: 12px;
  margin-bottom: 5px;
}

.tips p:last-child {
  margin-bottom: 0;
}
</style>

// suTT/frontend/src/components/Login.jsx

import React, { useState } from 'react';
import axios from 'axios';

function Login({ onLogin }) {
  const [isRegister, setIsRegister] = useState(false);
  const [formData, setFormData] = useState({
    username: '',
    password: '',
    phone: '',
    email: '',
    code: ''
  });
  const [error, setError] = useState('');

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    
    try {
      let response;
      if (isRegister) {
        response = await axios.post('http://localhost:8080/api/auth/register', formData);
      } else {
        response = await axios.post('http://localhost:8080/api/auth/login', {
          account: formData.username,
          password: formData.password
        });
      }
      
      if (response.data.code === 200) {
        localStorage.setItem('token', response.data.data.token);
        localStorage.setItem('user', JSON.stringify(response.data.data.user));
        onLogin(response.data.data.user);
      }
    } catch (err) {
      setError(err.response?.data?.message || '操作失败');
    }
  };

  return (
    <div className="login-container">
      <div className="login-box">
        <h2>{isRegister ? '注册' : '登录'}</h2>
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label>{isRegister ? '用户名' : '账号'}</label>
            <input
              type="text"
              name="username"
              value={formData.username}
              onChange={handleChange}
              placeholder={isRegister ? '请输入用户名' : '请输入账号/手机号/邮箱'}
              required
            />
          </div>
          
          <div className="form-group">
            <label>密码</label>
            <input
              type="password"
              name="password"
              value={formData.password}
              onChange={handleChange}
              placeholder="请输入密码"
              required
            />
          </div>
          
          {isRegister && (
            <>
              <div className="form-group">
                <label>手机号（可选）</label>
                <input
                  type="text"
                  name="phone"
                  value={formData.phone}
                  onChange={handleChange}
                  placeholder="请输入手机号"
                />
              </div>
              <div className="form-group">
                <label>邮箱（可选）</label>
                <input
                  type="email"
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                  placeholder="请输入邮箱"
                />
              </div>
            </>
          )}
          
          {error && <div className="error-message">{error}</div>}
          
          <button type="submit" className="btn btn-primary">
            {isRegister ? '注册' : '登录'}
          </button>
        </form>
        
        <div className="toggle-link">
          <a href="#" onClick={(e) => { e.preventDefault(); setIsRegister(!isRegister); }}>
            {isRegister ? '已有账号？立即登录' : '没有账号？立即注册'}
          </a>
        </div>
      </div>
    </div>
  );
}

export default Login;
